package com.letv.cdn.openapi.dao.openapi;

import com.letv.cdn.openapi.pojo.ApiDomain;
import com.letv.cdn.openapi.pojo.ApiDomainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int countByExample(ApiDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int deleteByExample(ApiDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int insert(ApiDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int insertSelective(ApiDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    List<ApiDomain> selectByExample(ApiDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    ApiDomain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") ApiDomain record, @Param("example") ApiDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int updateByExample(@Param("record") ApiDomain record, @Param("example") ApiDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int updateByPrimaryKeySelective(ApiDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Thu Dec 11 13:53:28 CST 2014
     */
    int updateByPrimaryKey(ApiDomain record);
}