package com.letv.cdn.openapi.dao.openapi;

import com.letv.cdn.openapi.pojo.CdnResourceLimit;
import com.letv.cdn.openapi.pojo.CdnResourceLimitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdnResourceLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int countByExample(CdnResourceLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int deleteByExample(CdnResourceLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int insert(CdnResourceLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int insertSelective(CdnResourceLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    List<CdnResourceLimit> selectByExample(CdnResourceLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    CdnResourceLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") CdnResourceLimit record, @Param("example") CdnResourceLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int updateByExample(@Param("record") CdnResourceLimit record, @Param("example") CdnResourceLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int updateByPrimaryKeySelective(CdnResourceLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    int updateByPrimaryKey(CdnResourceLimit record);
}