package com.letv.cdn.openapi.dao.openapi;

import com.letv.cdn.openapi.pojo.PreDistTask;
import com.letv.cdn.openapi.pojo.PreDistTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreDistTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int countByExample(PreDistTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int deleteByExample(PreDistTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int insert(PreDistTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int insertSelective(PreDistTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    List<PreDistTask> selectByExample(PreDistTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    PreDistTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") PreDistTask record, @Param("example") PreDistTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int updateByExample(@Param("record") PreDistTask record, @Param("example") PreDistTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int updateByPrimaryKeySelective(PreDistTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    int updateByPrimaryKey(PreDistTask record);
    
    /**
     * 按src关键字、statu、tasktag 分页查询
     * @param example
     * @return
     */
    List<PreDistTask> selectBySrcAndStatusPagination(PreDistTaskExample example);
    
}