package com.letv.cdn.openapi.dao.openapi;

import com.letv.cdn.openapi.pojo.PreDistParam;
import com.letv.cdn.openapi.pojo.PreDistParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreDistParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int countByExample(PreDistParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int deleteByExample(PreDistParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int insert(PreDistParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int insertSelective(PreDistParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    List<PreDistParam> selectByExample(PreDistParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    PreDistParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") PreDistParam record, @Param("example") PreDistParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int updateByExample(@Param("record") PreDistParam record, @Param("example") PreDistParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int updateByPrimaryKeySelective(PreDistParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_param
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    int updateByPrimaryKey(PreDistParam record);
}