package com.letv.cdn.openapi.pojo;

public class CdnResourceLimit {
	
	/**
	 * 限制的对象-域名
	 */
	public static final String LIMITED_OBJ_DOMAIN = "domain";
	
	/**
	 * 限制的对象-用户
	 */
	public static final String LIMITED_OBJ_USER = "user";
	
	/**
	 * 限制的资源-预分发任务
	 */
	public static final String RESOURCE_TASK = "pre_dist_task";
	
	/**
	 * 限制的资源-加速域名
	 */
	public static final String RESOURCE_DOMAIN = "domain";
	
	/**
	 * 限制的模式-存储数量
	 */
	public static final String LIMITED_MODE_STORAGE = "storage";
	
	/**
	 * 限制的模式-操作次数
	 */
	public static final String LIMITED_MODE_OPERATION = "operation";
	
	/**
	 * 限制的时间频率-单日
	 */
	public static final String TIME_CYCLE_DAY = "day";
	
	/**
	 * 操作类型-新增
	 */
	public static final Byte OPERATION_TYPE_INSERT = 0;
	
	/**
	 * 操作类型-更新
	 */
	public static final Byte OPERATION_TYPE_UPDATE = 1;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.id
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.limited_obj
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private String limitedObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.limited_obj_id
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private String limitedObjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.resource
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.limited_mode
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private String limitedMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.limited_value
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private Integer limitedValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdn_resource_limit.time_cycle
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    private String timeCycle;
    
    /**
     * 操作类型
     */
    private Byte operationType;
    
    /**
     * 备注
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.id
     *
     * @return the value of cdn_resource_limit.id
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.id
     *
     * @param id the value for cdn_resource_limit.id
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.limited_obj
     *
     * @return the value of cdn_resource_limit.limited_obj
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public String getLimitedObj() {
        return limitedObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.limited_obj
     *
     * @param limitedObj the value for cdn_resource_limit.limited_obj
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setLimitedObj(String limitedObj) {
        this.limitedObj = limitedObj == null ? null : limitedObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.limited_obj_id
     *
     * @return the value of cdn_resource_limit.limited_obj_id
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public String getLimitedObjId() {
        return limitedObjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.limited_obj_id
     *
     * @param limitedObjId the value for cdn_resource_limit.limited_obj_id
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setLimitedObjId(String limitedObjId) {
        this.limitedObjId = limitedObjId == null ? null : limitedObjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.resource
     *
     * @return the value of cdn_resource_limit.resource
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.resource
     *
     * @param resource the value for cdn_resource_limit.resource
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.limited_mode
     *
     * @return the value of cdn_resource_limit.limited_mode
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public String getLimitedMode() {
        return limitedMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.limited_mode
     *
     * @param limitedMode the value for cdn_resource_limit.limited_mode
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setLimitedMode(String limitedMode) {
        this.limitedMode = limitedMode == null ? null : limitedMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.limited_value
     *
     * @return the value of cdn_resource_limit.limited_value
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public Integer getLimitedValue() {
        return limitedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.limited_value
     *
     * @param limitedValue the value for cdn_resource_limit.limited_value
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setLimitedValue(Integer limitedValue) {
        this.limitedValue = limitedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdn_resource_limit.time_cycle
     *
     * @return the value of cdn_resource_limit.time_cycle
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public String getTimeCycle() {
        return timeCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdn_resource_limit.time_cycle
     *
     * @param timeCycle the value for cdn_resource_limit.time_cycle
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setTimeCycle(String timeCycle) {
        this.timeCycle = timeCycle == null ? null : timeCycle.trim();
    }

	public Byte getOperationType() {
		return operationType;
	}

	public void setOperationType(Byte operationType) {
		this.operationType = operationType;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}