package com.letv.cdn.openapi.pojo;

import java.util.ArrayList;
import java.util.List;

import com.letv.cdn.openapiauth.pojo.OpenapiExample.Criteria;

public class CdnResourceLimitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    protected int[] limit = new int[] {-1, -1};

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public CdnResourceLimitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setLimitValue1(int val) {
        this.limit[0] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public void setLimitValue2(int val) {
        this.limit[1] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public int getLimitValue1() {
        return this.limit[0];
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public int getLimitValue2() {
        return this.limit[1];
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIsNull() {
            addCriterion("limited_obj is null");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIsNotNull() {
            addCriterion("limited_obj is not null");
            return (Criteria) this;
        }

        public Criteria andLimitedObjEqualTo(String value) {
            addCriterion("limited_obj =", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjNotEqualTo(String value) {
            addCriterion("limited_obj <>", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjGreaterThan(String value) {
            addCriterion("limited_obj >", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjGreaterThanOrEqualTo(String value) {
            addCriterion("limited_obj >=", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjLessThan(String value) {
            addCriterion("limited_obj <", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjLessThanOrEqualTo(String value) {
            addCriterion("limited_obj <=", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjLike(String value) {
            addCriterion("limited_obj like", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjNotLike(String value) {
            addCriterion("limited_obj not like", value, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIn(List<String> values) {
            addCriterion("limited_obj in", values, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjNotIn(List<String> values) {
            addCriterion("limited_obj not in", values, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjBetween(String value1, String value2) {
            addCriterion("limited_obj between", value1, value2, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjNotBetween(String value1, String value2) {
            addCriterion("limited_obj not between", value1, value2, "limitedObj");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdIsNull() {
            addCriterion("limited_obj_id is null");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdIsNotNull() {
            addCriterion("limited_obj_id is not null");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdEqualTo(String value) {
            addCriterion("limited_obj_id =", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdNotEqualTo(String value) {
            addCriterion("limited_obj_id <>", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdGreaterThan(String value) {
            addCriterion("limited_obj_id >", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdGreaterThanOrEqualTo(String value) {
            addCriterion("limited_obj_id >=", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdLessThan(String value) {
            addCriterion("limited_obj_id <", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdLessThanOrEqualTo(String value) {
            addCriterion("limited_obj_id <=", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdLike(String value) {
            addCriterion("limited_obj_id like", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdNotLike(String value) {
            addCriterion("limited_obj_id not like", value, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdIn(List<String> values) {
            addCriterion("limited_obj_id in", values, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdNotIn(List<String> values) {
            addCriterion("limited_obj_id not in", values, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdBetween(String value1, String value2) {
            addCriterion("limited_obj_id between", value1, value2, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andLimitedObjIdNotBetween(String value1, String value2) {
            addCriterion("limited_obj_id not between", value1, value2, "limitedObjId");
            return (Criteria) this;
        }

        public Criteria andResourceIsNull() {
            addCriterion("resource is null");
            return (Criteria) this;
        }

        public Criteria andResourceIsNotNull() {
            addCriterion("resource is not null");
            return (Criteria) this;
        }

        public Criteria andResourceEqualTo(String value) {
            addCriterion("resource =", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotEqualTo(String value) {
            addCriterion("resource <>", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceGreaterThan(String value) {
            addCriterion("resource >", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceGreaterThanOrEqualTo(String value) {
            addCriterion("resource >=", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLessThan(String value) {
            addCriterion("resource <", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLessThanOrEqualTo(String value) {
            addCriterion("resource <=", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLike(String value) {
            addCriterion("resource like", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotLike(String value) {
            addCriterion("resource not like", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceIn(List<String> values) {
            addCriterion("resource in", values, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotIn(List<String> values) {
            addCriterion("resource not in", values, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceBetween(String value1, String value2) {
            addCriterion("resource between", value1, value2, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotBetween(String value1, String value2) {
            addCriterion("resource not between", value1, value2, "resource");
            return (Criteria) this;
        }

        public Criteria andLimitedModeIsNull() {
            addCriterion("limited_mode is null");
            return (Criteria) this;
        }

        public Criteria andLimitedModeIsNotNull() {
            addCriterion("limited_mode is not null");
            return (Criteria) this;
        }

        public Criteria andLimitedModeEqualTo(String value) {
            addCriterion("limited_mode =", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeNotEqualTo(String value) {
            addCriterion("limited_mode <>", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeGreaterThan(String value) {
            addCriterion("limited_mode >", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeGreaterThanOrEqualTo(String value) {
            addCriterion("limited_mode >=", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeLessThan(String value) {
            addCriterion("limited_mode <", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeLessThanOrEqualTo(String value) {
            addCriterion("limited_mode <=", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeLike(String value) {
            addCriterion("limited_mode like", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeNotLike(String value) {
            addCriterion("limited_mode not like", value, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeIn(List<String> values) {
            addCriterion("limited_mode in", values, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeNotIn(List<String> values) {
            addCriterion("limited_mode not in", values, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeBetween(String value1, String value2) {
            addCriterion("limited_mode between", value1, value2, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedModeNotBetween(String value1, String value2) {
            addCriterion("limited_mode not between", value1, value2, "limitedMode");
            return (Criteria) this;
        }

        public Criteria andLimitedValueIsNull() {
            addCriterion("limited_value is null");
            return (Criteria) this;
        }

        public Criteria andLimitedValueIsNotNull() {
            addCriterion("limited_value is not null");
            return (Criteria) this;
        }

        public Criteria andLimitedValueEqualTo(Integer value) {
            addCriterion("limited_value =", value, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueNotEqualTo(Integer value) {
            addCriterion("limited_value <>", value, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueGreaterThan(Integer value) {
            addCriterion("limited_value >", value, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("limited_value >=", value, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueLessThan(Integer value) {
            addCriterion("limited_value <", value, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueLessThanOrEqualTo(Integer value) {
            addCriterion("limited_value <=", value, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueIn(List<Integer> values) {
            addCriterion("limited_value in", values, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueNotIn(List<Integer> values) {
            addCriterion("limited_value not in", values, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueBetween(Integer value1, Integer value2) {
            addCriterion("limited_value between", value1, value2, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andLimitedValueNotBetween(Integer value1, Integer value2) {
            addCriterion("limited_value not between", value1, value2, "limitedValue");
            return (Criteria) this;
        }

        public Criteria andTimeCycleIsNull() {
            addCriterion("time_cycle is null");
            return (Criteria) this;
        }

        public Criteria andTimeCycleIsNotNull() {
            addCriterion("time_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andTimeCycleEqualTo(String value) {
            addCriterion("time_cycle =", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleNotEqualTo(String value) {
            addCriterion("time_cycle <>", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleGreaterThan(String value) {
            addCriterion("time_cycle >", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleGreaterThanOrEqualTo(String value) {
            addCriterion("time_cycle >=", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleLessThan(String value) {
            addCriterion("time_cycle <", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleLessThanOrEqualTo(String value) {
            addCriterion("time_cycle <=", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleLike(String value) {
            addCriterion("time_cycle like", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleNotLike(String value) {
            addCriterion("time_cycle not like", value, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleIn(List<String> values) {
            addCriterion("time_cycle in", values, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleNotIn(List<String> values) {
            addCriterion("time_cycle not in", values, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleBetween(String value1, String value2) {
            addCriterion("time_cycle between", value1, value2, "timeCycle");
            return (Criteria) this;
        }

        public Criteria andTimeCycleNotBetween(String value1, String value2) {
            addCriterion("time_cycle not between", value1, value2, "timeCycle");
            return (Criteria) this;
        }
        
        public Criteria andOperationTypeEqualTo(Byte value) {
       	 	addCriterion("operation_type =", value, "operationType");
            return (Criteria) this;
        }
        
        public Criteria andOperationTypeIsNull() {
            addCriterion("operation_type is null");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 09 14:33:28 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cdn_resource_limit
     *
     * @mbggenerated Tue Dec 09 14:33:28 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}