package com.letv.cdn.openapi.pojo;

import java.util.ArrayList;
import java.util.List;

public class CoopDomainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    protected int[] limit = new int[] {-1, -1};

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public CoopDomainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public void setLimitValue1(int val) {
        this.limit[0] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public void setLimitValue2(int val) {
        this.limit[1] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public int getLimitValue1() {
        return this.limit[0];
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public int getLimitValue2() {
        return this.limit[1];
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDomainIsNull() {
            addCriterion("DOMAIN is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("DOMAIN is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("DOMAIN =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("DOMAIN <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("DOMAIN >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("DOMAIN >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("DOMAIN <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("DOMAIN <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("DOMAIN like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("DOMAIN not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("DOMAIN in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("DOMAIN not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("DOMAIN between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("DOMAIN not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUsertagIsNull() {
            addCriterion("USERTAG is null");
            return (Criteria) this;
        }

        public Criteria andUsertagIsNotNull() {
            addCriterion("USERTAG is not null");
            return (Criteria) this;
        }

        public Criteria andUsertagEqualTo(String value) {
            addCriterion("USERTAG =", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagNotEqualTo(String value) {
            addCriterion("USERTAG <>", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagGreaterThan(String value) {
            addCriterion("USERTAG >", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagGreaterThanOrEqualTo(String value) {
            addCriterion("USERTAG >=", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagLessThan(String value) {
            addCriterion("USERTAG <", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagLessThanOrEqualTo(String value) {
            addCriterion("USERTAG <=", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagLike(String value) {
            addCriterion("USERTAG like", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagNotLike(String value) {
            addCriterion("USERTAG not like", value, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagIn(List<String> values) {
            addCriterion("USERTAG in", values, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagNotIn(List<String> values) {
            addCriterion("USERTAG not in", values, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagBetween(String value1, String value2) {
            addCriterion("USERTAG between", value1, value2, "usertag");
            return (Criteria) this;
        }

        public Criteria andUsertagNotBetween(String value1, String value2) {
            addCriterion("USERTAG not between", value1, value2, "usertag");
            return (Criteria) this;
        }

        public Criteria andFrontcdnIsNull() {
            addCriterion("FRONTCDN is null");
            return (Criteria) this;
        }

        public Criteria andFrontcdnIsNotNull() {
            addCriterion("FRONTCDN is not null");
            return (Criteria) this;
        }

        public Criteria andFrontcdnEqualTo(String value) {
            addCriterion("FRONTCDN =", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnNotEqualTo(String value) {
            addCriterion("FRONTCDN <>", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnGreaterThan(String value) {
            addCriterion("FRONTCDN >", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnGreaterThanOrEqualTo(String value) {
            addCriterion("FRONTCDN >=", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnLessThan(String value) {
            addCriterion("FRONTCDN <", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnLessThanOrEqualTo(String value) {
            addCriterion("FRONTCDN <=", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnLike(String value) {
            addCriterion("FRONTCDN like", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnNotLike(String value) {
            addCriterion("FRONTCDN not like", value, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnIn(List<String> values) {
            addCriterion("FRONTCDN in", values, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnNotIn(List<String> values) {
            addCriterion("FRONTCDN not in", values, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnBetween(String value1, String value2) {
            addCriterion("FRONTCDN between", value1, value2, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andFrontcdnNotBetween(String value1, String value2) {
            addCriterion("FRONTCDN not between", value1, value2, "frontcdn");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSrcdxIsNull() {
            addCriterion("SRCDX is null");
            return (Criteria) this;
        }

        public Criteria andSrcdxIsNotNull() {
            addCriterion("SRCDX is not null");
            return (Criteria) this;
        }

        public Criteria andSrcdxEqualTo(String value) {
            addCriterion("SRCDX =", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxNotEqualTo(String value) {
            addCriterion("SRCDX <>", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxGreaterThan(String value) {
            addCriterion("SRCDX >", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxGreaterThanOrEqualTo(String value) {
            addCriterion("SRCDX >=", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxLessThan(String value) {
            addCriterion("SRCDX <", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxLessThanOrEqualTo(String value) {
            addCriterion("SRCDX <=", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxLike(String value) {
            addCriterion("SRCDX like", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxNotLike(String value) {
            addCriterion("SRCDX not like", value, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxIn(List<String> values) {
            addCriterion("SRCDX in", values, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxNotIn(List<String> values) {
            addCriterion("SRCDX not in", values, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxBetween(String value1, String value2) {
            addCriterion("SRCDX between", value1, value2, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcdxNotBetween(String value1, String value2) {
            addCriterion("SRCDX not between", value1, value2, "srcdx");
            return (Criteria) this;
        }

        public Criteria andSrcltIsNull() {
            addCriterion("SRCLT is null");
            return (Criteria) this;
        }

        public Criteria andSrcltIsNotNull() {
            addCriterion("SRCLT is not null");
            return (Criteria) this;
        }

        public Criteria andSrcltEqualTo(String value) {
            addCriterion("SRCLT =", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltNotEqualTo(String value) {
            addCriterion("SRCLT <>", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltGreaterThan(String value) {
            addCriterion("SRCLT >", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltGreaterThanOrEqualTo(String value) {
            addCriterion("SRCLT >=", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltLessThan(String value) {
            addCriterion("SRCLT <", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltLessThanOrEqualTo(String value) {
            addCriterion("SRCLT <=", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltLike(String value) {
            addCriterion("SRCLT like", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltNotLike(String value) {
            addCriterion("SRCLT not like", value, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltIn(List<String> values) {
            addCriterion("SRCLT in", values, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltNotIn(List<String> values) {
            addCriterion("SRCLT not in", values, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltBetween(String value1, String value2) {
            addCriterion("SRCLT between", value1, value2, "srclt");
            return (Criteria) this;
        }

        public Criteria andSrcltNotBetween(String value1, String value2) {
            addCriterion("SRCLT not between", value1, value2, "srclt");
            return (Criteria) this;
        }

        public Criteria andQueryhostIsNull() {
            addCriterion("QUERYHOST is null");
            return (Criteria) this;
        }

        public Criteria andQueryhostIsNotNull() {
            addCriterion("QUERYHOST is not null");
            return (Criteria) this;
        }

        public Criteria andQueryhostEqualTo(String value) {
            addCriterion("QUERYHOST =", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostNotEqualTo(String value) {
            addCriterion("QUERYHOST <>", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostGreaterThan(String value) {
            addCriterion("QUERYHOST >", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostGreaterThanOrEqualTo(String value) {
            addCriterion("QUERYHOST >=", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostLessThan(String value) {
            addCriterion("QUERYHOST <", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostLessThanOrEqualTo(String value) {
            addCriterion("QUERYHOST <=", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostLike(String value) {
            addCriterion("QUERYHOST like", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostNotLike(String value) {
            addCriterion("QUERYHOST not like", value, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostIn(List<String> values) {
            addCriterion("QUERYHOST in", values, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostNotIn(List<String> values) {
            addCriterion("QUERYHOST not in", values, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostBetween(String value1, String value2) {
            addCriterion("QUERYHOST between", value1, value2, "queryhost");
            return (Criteria) this;
        }

        public Criteria andQueryhostNotBetween(String value1, String value2) {
            addCriterion("QUERYHOST not between", value1, value2, "queryhost");
            return (Criteria) this;
        }

        public Criteria andSrcispIsNull() {
            addCriterion("SRCISP is null");
            return (Criteria) this;
        }

        public Criteria andSrcispIsNotNull() {
            addCriterion("SRCISP is not null");
            return (Criteria) this;
        }

        public Criteria andSrcispEqualTo(Short value) {
            addCriterion("SRCISP =", value, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispNotEqualTo(Short value) {
            addCriterion("SRCISP <>", value, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispGreaterThan(Short value) {
            addCriterion("SRCISP >", value, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispGreaterThanOrEqualTo(Short value) {
            addCriterion("SRCISP >=", value, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispLessThan(Short value) {
            addCriterion("SRCISP <", value, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispLessThanOrEqualTo(Short value) {
            addCriterion("SRCISP <=", value, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispIn(List<Short> values) {
            addCriterion("SRCISP in", values, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispNotIn(List<Short> values) {
            addCriterion("SRCISP not in", values, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispBetween(Short value1, Short value2) {
            addCriterion("SRCISP between", value1, value2, "srcisp");
            return (Criteria) this;
        }

        public Criteria andSrcispNotBetween(Short value1, Short value2) {
            addCriterion("SRCISP not between", value1, value2, "srcisp");
            return (Criteria) this;
        }

        public Criteria andActionIsNull() {
            addCriterion("ACTION is null");
            return (Criteria) this;
        }

        public Criteria andActionIsNotNull() {
            addCriterion("ACTION is not null");
            return (Criteria) this;
        }

        public Criteria andActionEqualTo(Short value) {
            addCriterion("ACTION =", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotEqualTo(Short value) {
            addCriterion("ACTION <>", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThan(Short value) {
            addCriterion("ACTION >", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThanOrEqualTo(Short value) {
            addCriterion("ACTION >=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThan(Short value) {
            addCriterion("ACTION <", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThanOrEqualTo(Short value) {
            addCriterion("ACTION <=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionIn(List<Short> values) {
            addCriterion("ACTION in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotIn(List<Short> values) {
            addCriterion("ACTION not in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionBetween(Short value1, Short value2) {
            addCriterion("ACTION between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotBetween(Short value1, Short value2) {
            addCriterion("ACTION not between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andOntestIsNull() {
            addCriterion("ONTEST is null");
            return (Criteria) this;
        }

        public Criteria andOntestIsNotNull() {
            addCriterion("ONTEST is not null");
            return (Criteria) this;
        }

        public Criteria andOntestEqualTo(Short value) {
            addCriterion("ONTEST =", value, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestNotEqualTo(Short value) {
            addCriterion("ONTEST <>", value, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestGreaterThan(Short value) {
            addCriterion("ONTEST >", value, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestGreaterThanOrEqualTo(Short value) {
            addCriterion("ONTEST >=", value, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestLessThan(Short value) {
            addCriterion("ONTEST <", value, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestLessThanOrEqualTo(Short value) {
            addCriterion("ONTEST <=", value, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestIn(List<Short> values) {
            addCriterion("ONTEST in", values, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestNotIn(List<Short> values) {
            addCriterion("ONTEST not in", values, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestBetween(Short value1, Short value2) {
            addCriterion("ONTEST between", value1, value2, "ontest");
            return (Criteria) this;
        }

        public Criteria andOntestNotBetween(Short value1, Short value2) {
            addCriterion("ONTEST not between", value1, value2, "ontest");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_coop_domain
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 01 11:09:06 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Mon Jun 01 11:09:06 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}