package com.letv.cdn.openapi.pojo;

import java.util.Date;

public class DomainApply {
	
	/**
	 * 待审核
	 */
	public static final Short AUDIT_APPROVING = 0;
	
	/**
	 * 审核通过
	 */
	public static final Short AUDIT_ALLOWED = 1;
	
	/**
	 * 审核未通过
	 */
	public static final Short AUDIT_DENY = 2;
	
	/**
	 * 取消域名申请
	 */
	public static final Short AUDIT_CANCEL = 3;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.id
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.userid
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.domaintag
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String domaintag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.domain
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.source
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.service_type
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Short serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.contacts
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.contacts_phone
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String contactsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.contacts_email
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String contactsEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.service_status
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Short serviceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.create_time
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.auditor_id
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Integer auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.audit_time
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_apply.remark
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    private String remark;
    
    public DomainApply(){}
    
    

    public DomainApply(Integer userid, String domaintag, String domain,
			String source, Short serviceType, String contacts,
			String contactsPhone, String contactsEmail, String remark) {
		super();
		this.userid = userid;
		this.domaintag = domaintag;
		this.domain = domain;
		this.source = source;
		this.serviceType = serviceType;
		this.contacts = contacts;
		this.contactsPhone = contactsPhone;
		this.contactsEmail = contactsEmail;
		this.remark = remark;
	}



	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.id
     *
     * @return the value of domain_apply.id
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.id
     *
     * @param id the value for domain_apply.id
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.userid
     *
     * @return the value of domain_apply.userid
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.userid
     *
     * @param userid the value for domain_apply.userid
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.domaintag
     *
     * @return the value of domain_apply.domaintag
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getDomaintag() {
        return domaintag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.domaintag
     *
     * @param domaintag the value for domain_apply.domaintag
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setDomaintag(String domaintag) {
        this.domaintag = domaintag == null ? null : domaintag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.domain
     *
     * @return the value of domain_apply.domain
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.domain
     *
     * @param domain the value for domain_apply.domain
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.source
     *
     * @return the value of domain_apply.source
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.source
     *
     * @param source the value for domain_apply.source
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.service_type
     *
     * @return the value of domain_apply.service_type
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Short getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.service_type
     *
     * @param serviceType the value for domain_apply.service_type
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setServiceType(Short serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.contacts
     *
     * @return the value of domain_apply.contacts
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.contacts
     *
     * @param contacts the value for domain_apply.contacts
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.contacts_phone
     *
     * @return the value of domain_apply.contacts_phone
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getContactsPhone() {
        return contactsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.contacts_phone
     *
     * @param contactsPhone the value for domain_apply.contacts_phone
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setContactsPhone(String contactsPhone) {
        this.contactsPhone = contactsPhone == null ? null : contactsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.contacts_email
     *
     * @return the value of domain_apply.contacts_email
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getContactsEmail() {
        return contactsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.contacts_email
     *
     * @param contactsEmail the value for domain_apply.contacts_email
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setContactsEmail(String contactsEmail) {
        this.contactsEmail = contactsEmail == null ? null : contactsEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.service_status
     *
     * @return the value of domain_apply.service_status
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Short getServiceStatus() {
        return serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.service_status
     *
     * @param serviceStatus the value for domain_apply.service_status
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setServiceStatus(Short serviceStatus) {
        this.serviceStatus = serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.create_time
     *
     * @return the value of domain_apply.create_time
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.create_time
     *
     * @param createTime the value for domain_apply.create_time
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.auditor_id
     *
     * @return the value of domain_apply.auditor_id
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Integer getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.auditor_id
     *
     * @param auditorId the value for domain_apply.auditor_id
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setAuditorId(Integer auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.audit_time
     *
     * @return the value of domain_apply.audit_time
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.audit_time
     *
     * @param auditTime the value for domain_apply.audit_time
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_apply.remark
     *
     * @return the value of domain_apply.remark
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_apply.remark
     *
     * @param remark the value for domain_apply.remark
     *
     * @mbggenerated Fri Dec 12 16:51:49 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}