package com.letv.cdn.openapi.pojo;

import java.util.ArrayList;
import java.util.List;

public class DomainExtensionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    protected int[] limit = new int[] {-1, -1};

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public DomainExtensionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setLimitValue1(int val) {
        this.limit[0] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setLimitValue2(int val) {
        this.limit[1] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public int getLimitValue1() {
        return this.limit[0];
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public int getLimitValue2() {
        return this.limit[1];
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDomaintagIsNull() {
            addCriterion("domaintag is null");
            return (Criteria) this;
        }

        public Criteria andDomaintagIsNotNull() {
            addCriterion("domaintag is not null");
            return (Criteria) this;
        }

        public Criteria andDomaintagEqualTo(String value) {
            addCriterion("domaintag =", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotEqualTo(String value) {
            addCriterion("domaintag <>", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagGreaterThan(String value) {
            addCriterion("domaintag >", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagGreaterThanOrEqualTo(String value) {
            addCriterion("domaintag >=", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagLessThan(String value) {
            addCriterion("domaintag <", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagLessThanOrEqualTo(String value) {
            addCriterion("domaintag <=", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagLike(String value) {
            addCriterion("domaintag like", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotLike(String value) {
            addCriterion("domaintag not like", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagIn(List<String> values) {
            addCriterion("domaintag in", values, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotIn(List<String> values) {
            addCriterion("domaintag not in", values, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagBetween(String value1, String value2) {
            addCriterion("domaintag between", value1, value2, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotBetween(String value1, String value2) {
            addCriterion("domaintag not between", value1, value2, "domaintag");
            return (Criteria) this;
        }

        public Criteria andFilterDomainIsNull() {
            addCriterion("filter_domain is null");
            return (Criteria) this;
        }

        public Criteria andFilterDomainIsNotNull() {
            addCriterion("filter_domain is not null");
            return (Criteria) this;
        }

        public Criteria andFilterDomainEqualTo(String value) {
            addCriterion("filter_domain =", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainNotEqualTo(String value) {
            addCriterion("filter_domain <>", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainGreaterThan(String value) {
            addCriterion("filter_domain >", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainGreaterThanOrEqualTo(String value) {
            addCriterion("filter_domain >=", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainLessThan(String value) {
            addCriterion("filter_domain <", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainLessThanOrEqualTo(String value) {
            addCriterion("filter_domain <=", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainLike(String value) {
            addCriterion("filter_domain like", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainNotLike(String value) {
            addCriterion("filter_domain not like", value, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainIn(List<String> values) {
            addCriterion("filter_domain in", values, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainNotIn(List<String> values) {
            addCriterion("filter_domain not in", values, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainBetween(String value1, String value2) {
            addCriterion("filter_domain between", value1, value2, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andFilterDomainNotBetween(String value1, String value2) {
            addCriterion("filter_domain not between", value1, value2, "filterDomain");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table domain_extention
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 16:46:02 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table domain_extention
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}