package com.letv.cdn.openapi.pojo;

import com.alibaba.fastjson.JSONObject;

public class Domain {
    public static final String TYPE_CDN = "cdn";
    public static final String TYPE_CLOUD = "cloud";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.id
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.userid
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.tag
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.type
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.id
     *
     * @return the value of domain.id
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.id
     *
     * @param id the value for domain.id
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.userid
     *
     * @return the value of domain.userid
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.userid
     *
     * @param userid the value for domain.userid
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.domain
     *
     * @return the value of domain.domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.domain
     *
     * @param domain the value for domain.domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.tag
     *
     * @return the value of domain.tag
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.tag
     *
     * @param tag the value for domain.tag
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.type
     *
     * @return the value of domain.type
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.type
     *
     * @param type the value for domain.type
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    
    @Override
    public String toString() {
        return ((JSONObject)JSONObject.toJSON(this)).toJSONString();
    }
}