package com.letv.cdn.openapi.pojo;

public class DomainExtension {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_extention.id
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_extention.domaintag
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    private String domaintag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_extention.filter_domain
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    private String filterDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_extention.remark
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_extention.id
     *
     * @return the value of domain_extention.id
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_extention.id
     *
     * @param id the value for domain_extention.id
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_extention.domaintag
     *
     * @return the value of domain_extention.domaintag
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public String getDomaintag() {
        return domaintag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_extention.domaintag
     *
     * @param domaintag the value for domain_extention.domaintag
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setDomaintag(String domaintag) {
        this.domaintag = domaintag == null ? null : domaintag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_extention.filter_domain
     *
     * @return the value of domain_extention.filter_domain
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public String getFilterDomain() {
        return filterDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_extention.filter_domain
     *
     * @param filterDomain the value for domain_extention.filter_domain
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setFilterDomain(String filterDomain) {
        this.filterDomain = filterDomain == null ? null : filterDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_extention.remark
     *
     * @return the value of domain_extention.remark
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_extention.remark
     *
     * @param remark the value for domain_extention.remark
     *
     * @mbggenerated Mon May 18 16:46:02 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}