package com.letv.cdn.openapi.pojo;

public class PreDistParam {
	
	/**
	 * 不需要回调
	 */
	public static final byte CALLBACK_MODE_NONE = 0;
	
	/**
	 * 中心节点分发时回调
	 */
	public static final byte CALLBACK_MODE_CENTER = 1;
	
	/**
	 * 中心节点和全局节点分发时均回调
	 */
	public static final byte CALLBACK_MODE_GLOBAL = 2;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.id
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.appkey
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private String appkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.prop
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private String prop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.priority
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.region
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private String region;
    
    /**
     * 回调模式
     */
    private Byte callbackMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.callback
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private String callback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_param.remark
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.id
     *
     * @return the value of pre_dist_param.id
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.id
     *
     * @param id the value for pre_dist_param.id
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.appkey
     *
     * @return the value of pre_dist_param.appkey
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.appkey
     *
     * @param appkey the value for pre_dist_param.appkey
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.prop
     *
     * @return the value of pre_dist_param.prop
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public String getProp() {
        return prop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.prop
     *
     * @param prop the value for pre_dist_param.prop
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setProp(String prop) {
        this.prop = prop == null ? null : prop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.priority
     *
     * @return the value of pre_dist_param.priority
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.priority
     *
     * @param priority the value for pre_dist_param.priority
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.region
     *
     * @return the value of pre_dist_param.region
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.region
     *
     * @param region the value for pre_dist_param.region
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.callback
     *
     * @return the value of pre_dist_param.callback
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public String getCallback() {
        return callback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.callback
     *
     * @param callback the value for pre_dist_param.callback
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setCallback(String callback) {
        this.callback = callback == null ? null : callback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_param.remark
     *
     * @return the value of pre_dist_param.remark
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_param.remark
     *
     * @param remark the value for pre_dist_param.remark
     *
     * @mbggenerated Sun Jan 04 17:39:04 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public Byte getCallbackMode() {
		return callbackMode;
	}

	public void setCallbackMode(Byte callbackMode) {
		this.callbackMode = callbackMode;
	}
}