package com.letv.cdn.openapi.pojo;

import java.util.Date;

public class PreDistTask {
	
	 /** 分发中 */
    public static final Byte STATUS_ING = 2;
    /** 分发成功 */
    public static final Byte STATUS_SUCCESS = 1;
    /** 分发失败 */
    public static final Byte STATUS_FAILURE = 0;
    /** 分发失败，重试中 */
    public static final Byte STATUS_FAILURE_RETRY = 3;
    /** 已删除 */
    public static final Byte STATUS_DELETED = 4;
    /** 预分发任务提交失败*/
	public static final Byte SUB_FAIL = 6;
	/** 预分发任务重复*/
	public static final Byte TASK_REPEAT = 5;
	
	/**
	 * 待提交
	 */
	public static final Byte STATUS_PRE_SUBMIT = 7;
	
	/**
	 * src重复
	 */
	public static final Byte STATUS_SRC_REPEAT = 8;
	
	/**
	 * 已完成全网分发
	 */
	public static final Byte STATUS_GLOBAL_DIST = 9;
	
    public static final String CALLBACK_CODE_SUCCESS = "200";
    /** 分发失败，重试中 */
    public static final String CALLBACK_CODE_FAILURE_RETRY = "403";
    /** 分发失败 */
    public static final String CALLBACK_CODE_FAILURE = "405";
    /**提交任务类型*/
    public static final String TASK_SUB_TYPE = "submit";
    /**刷新任务类型*/
    public static final String TASK_REFRESH ="refresh";
    
    /**
     * 未回调客户
     */
    public static final Byte CLIENT_CALLBACK_NONE = 0;
	
    /**
     * 回调客户-中心节点分发完成
     */
    public static final Byte CLIENT_CALLBACK_CENTER = 1;
    
    /**
     * 回调客户-全网分发完成
     */
    public static final Byte CLIENT_CALLBACK_GLOBAL = 2;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.id
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.src
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.outkey
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String outkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.md5
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.userid
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.appkey
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String appkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.domaintag
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String domaintag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.status
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.create_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.callback_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Long callbackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.callback_code
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String callbackCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.store_path
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String storePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.size
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.delete_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private Long deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.tasktag
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String tasktag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_dist_task.task_type
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    private String taskType;
    
    /**
     * 临时字段，用于提交任务
     */
    private Long version;
    
    private Byte clientCallbacked;
    
    private Date clientCallbackTime;

    public Byte getClientCallbacked() {
		return clientCallbacked;
	}

	public void setClientCallbacked(Byte clientCallbacked) {
		this.clientCallbacked = clientCallbacked;
	}

	public Date getClientCallbackTime() {
		return clientCallbackTime;
	}

	public void setClientCallbackTime(Date clientCallbackTime) {
		this.clientCallbackTime = clientCallbackTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.id
     *
     * @return the value of pre_dist_task.id
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.id
     *
     * @param id the value for pre_dist_task.id
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.src
     *
     * @return the value of pre_dist_task.src
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.src
     *
     * @param src the value for pre_dist_task.src
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.outkey
     *
     * @return the value of pre_dist_task.outkey
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getOutkey() {
        return outkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.outkey
     *
     * @param outkey the value for pre_dist_task.outkey
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setOutkey(String outkey) {
        this.outkey = outkey == null ? null : outkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.md5
     *
     * @return the value of pre_dist_task.md5
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.md5
     *
     * @param md5 the value for pre_dist_task.md5
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.userid
     *
     * @return the value of pre_dist_task.userid
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.userid
     *
     * @param userid the value for pre_dist_task.userid
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.appkey
     *
     * @return the value of pre_dist_task.appkey
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.appkey
     *
     * @param appkey the value for pre_dist_task.appkey
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.domaintag
     *
     * @return the value of pre_dist_task.domaintag
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getDomaintag() {
        return domaintag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.domaintag
     *
     * @param domaintag the value for pre_dist_task.domaintag
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setDomaintag(String domaintag) {
        this.domaintag = domaintag == null ? null : domaintag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.status
     *
     * @return the value of pre_dist_task.status
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.status
     *
     * @param status the value for pre_dist_task.status
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.create_time
     *
     * @return the value of pre_dist_task.create_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.create_time
     *
     * @param createTime the value for pre_dist_task.create_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.callback_time
     *
     * @return the value of pre_dist_task.callback_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Long getCallbackTime() {
        return callbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.callback_time
     *
     * @param callbackTime the value for pre_dist_task.callback_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setCallbackTime(Long callbackTime) {
        this.callbackTime = callbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.callback_code
     *
     * @return the value of pre_dist_task.callback_code
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getCallbackCode() {
        return callbackCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.callback_code
     *
     * @param callbackCode the value for pre_dist_task.callback_code
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setCallbackCode(String callbackCode) {
        this.callbackCode = callbackCode == null ? null : callbackCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.store_path
     *
     * @return the value of pre_dist_task.store_path
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getStorePath() {
        return storePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.store_path
     *
     * @param storePath the value for pre_dist_task.store_path
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setStorePath(String storePath) {
        this.storePath = storePath == null ? null : storePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.size
     *
     * @return the value of pre_dist_task.size
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.size
     *
     * @param size the value for pre_dist_task.size
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.delete_time
     *
     * @return the value of pre_dist_task.delete_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Long getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.delete_time
     *
     * @param deleteTime the value for pre_dist_task.delete_time
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setDeleteTime(Long deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.tasktag
     *
     * @return the value of pre_dist_task.tasktag
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getTasktag() {
        return tasktag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.tasktag
     *
     * @param tasktag the value for pre_dist_task.tasktag
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setTasktag(String tasktag) {
        this.tasktag = tasktag == null ? null : tasktag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_dist_task.task_type
     *
     * @return the value of pre_dist_task.task_type
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_dist_task.task_type
     *
     * @param taskType the value for pre_dist_task.task_type
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
}