package com.letv.cdn.openapi.pojo;

import java.util.ArrayList;
import java.util.List;

public class PreDistTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    protected int[] limit = new int[] {-1, -1};
    
    
    protected int begin =  -1 ;
    protected int totalSize =  -1 ;
    
    
    

    public int getBegin() {
		return begin;
	}

	public void setBegin(int begin) {
		this.begin = begin;
	}

	public int getTotalSize() {
		return totalSize;
	}

	public void setTotalSize(int totalSize) {
		this.totalSize = totalSize;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public PreDistTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setLimitValue1(int val) {
        this.limit[0] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public void setLimitValue2(int val) {
        this.limit[1] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public int getLimitValue1() {
        return this.limit[0];
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public int getLimitValue2() {
        return this.limit[1];
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSrcIsNull() {
            addCriterion("src is null");
            return (Criteria) this;
        }

        public Criteria andSrcIsNotNull() {
            addCriterion("src is not null");
            return (Criteria) this;
        }

        public Criteria andSrcEqualTo(String value) {
            addCriterion("src =", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotEqualTo(String value) {
            addCriterion("src <>", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcGreaterThan(String value) {
            addCriterion("src >", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcGreaterThanOrEqualTo(String value) {
            addCriterion("src >=", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLessThan(String value) {
            addCriterion("src <", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLessThanOrEqualTo(String value) {
            addCriterion("src <=", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLike(String value) {
            addCriterion("src like", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotLike(String value) {
            addCriterion("src not like", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcIn(List<String> values) {
            addCriterion("src in", values, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotIn(List<String> values) {
            addCriterion("src not in", values, "src");
            return (Criteria) this;
        }

        public Criteria andSrcBetween(String value1, String value2) {
            addCriterion("src between", value1, value2, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotBetween(String value1, String value2) {
            addCriterion("src not between", value1, value2, "src");
            return (Criteria) this;
        }

        public Criteria andOutkeyIsNull() {
            addCriterion("outkey is null");
            return (Criteria) this;
        }

        public Criteria andOutkeyIsNotNull() {
            addCriterion("outkey is not null");
            return (Criteria) this;
        }

        public Criteria andOutkeyEqualTo(String value) {
            addCriterion("outkey =", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyNotEqualTo(String value) {
            addCriterion("outkey <>", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyGreaterThan(String value) {
            addCriterion("outkey >", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyGreaterThanOrEqualTo(String value) {
            addCriterion("outkey >=", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyLessThan(String value) {
            addCriterion("outkey <", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyLessThanOrEqualTo(String value) {
            addCriterion("outkey <=", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyLike(String value) {
            addCriterion("outkey like", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyNotLike(String value) {
            addCriterion("outkey not like", value, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyIn(List<String> values) {
            addCriterion("outkey in", values, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyNotIn(List<String> values) {
            addCriterion("outkey not in", values, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyBetween(String value1, String value2) {
            addCriterion("outkey between", value1, value2, "outkey");
            return (Criteria) this;
        }

        public Criteria andOutkeyNotBetween(String value1, String value2) {
            addCriterion("outkey not between", value1, value2, "outkey");
            return (Criteria) this;
        }

        public Criteria andMd5IsNull() {
            addCriterion("md5 is null");
            return (Criteria) this;
        }

        public Criteria andMd5IsNotNull() {
            addCriterion("md5 is not null");
            return (Criteria) this;
        }

        public Criteria andMd5EqualTo(String value) {
            addCriterion("md5 =", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotEqualTo(String value) {
            addCriterion("md5 <>", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5GreaterThan(String value) {
            addCriterion("md5 >", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5GreaterThanOrEqualTo(String value) {
            addCriterion("md5 >=", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5LessThan(String value) {
            addCriterion("md5 <", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5LessThanOrEqualTo(String value) {
            addCriterion("md5 <=", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5Like(String value) {
            addCriterion("md5 like", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotLike(String value) {
            addCriterion("md5 not like", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5In(List<String> values) {
            addCriterion("md5 in", values, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotIn(List<String> values) {
            addCriterion("md5 not in", values, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5Between(String value1, String value2) {
            addCriterion("md5 between", value1, value2, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotBetween(String value1, String value2) {
            addCriterion("md5 not between", value1, value2, "md5");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAppkeyIsNull() {
            addCriterion("appkey is null");
            return (Criteria) this;
        }

        public Criteria andAppkeyIsNotNull() {
            addCriterion("appkey is not null");
            return (Criteria) this;
        }

        public Criteria andAppkeyEqualTo(String value) {
            addCriterion("appkey =", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotEqualTo(String value) {
            addCriterion("appkey <>", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyGreaterThan(String value) {
            addCriterion("appkey >", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyGreaterThanOrEqualTo(String value) {
            addCriterion("appkey >=", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyLessThan(String value) {
            addCriterion("appkey <", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyLessThanOrEqualTo(String value) {
            addCriterion("appkey <=", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyLike(String value) {
            addCriterion("appkey like", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotLike(String value) {
            addCriterion("appkey not like", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyIn(List<String> values) {
            addCriterion("appkey in", values, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotIn(List<String> values) {
            addCriterion("appkey not in", values, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyBetween(String value1, String value2) {
            addCriterion("appkey between", value1, value2, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotBetween(String value1, String value2) {
            addCriterion("appkey not between", value1, value2, "appkey");
            return (Criteria) this;
        }

        public Criteria andDomaintagIsNull() {
            addCriterion("domaintag is null");
            return (Criteria) this;
        }

        public Criteria andDomaintagIsNotNull() {
            addCriterion("domaintag is not null");
            return (Criteria) this;
        }

        public Criteria andDomaintagEqualTo(String value) {
            addCriterion("domaintag =", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotEqualTo(String value) {
            addCriterion("domaintag <>", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagGreaterThan(String value) {
            addCriterion("domaintag >", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagGreaterThanOrEqualTo(String value) {
            addCriterion("domaintag >=", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagLessThan(String value) {
            addCriterion("domaintag <", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagLessThanOrEqualTo(String value) {
            addCriterion("domaintag <=", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagLike(String value) {
            addCriterion("domaintag like", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotLike(String value) {
            addCriterion("domaintag not like", value, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagIn(List<String> values) {
            addCriterion("domaintag in", values, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotIn(List<String> values) {
            addCriterion("domaintag not in", values, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagBetween(String value1, String value2) {
            addCriterion("domaintag between", value1, value2, "domaintag");
            return (Criteria) this;
        }

        public Criteria andDomaintagNotBetween(String value1, String value2) {
            addCriterion("domaintag not between", value1, value2, "domaintag");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeIsNull() {
            addCriterion("callback_time is null");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeIsNotNull() {
            addCriterion("callback_time is not null");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeEqualTo(Long value) {
            addCriterion("callback_time =", value, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeNotEqualTo(Long value) {
            addCriterion("callback_time <>", value, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeGreaterThan(Long value) {
            addCriterion("callback_time >", value, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("callback_time >=", value, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeLessThan(Long value) {
            addCriterion("callback_time <", value, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeLessThanOrEqualTo(Long value) {
            addCriterion("callback_time <=", value, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeIn(List<Long> values) {
            addCriterion("callback_time in", values, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeNotIn(List<Long> values) {
            addCriterion("callback_time not in", values, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeBetween(Long value1, Long value2) {
            addCriterion("callback_time between", value1, value2, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackTimeNotBetween(Long value1, Long value2) {
            addCriterion("callback_time not between", value1, value2, "callbackTime");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeIsNull() {
            addCriterion("callback_code is null");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeIsNotNull() {
            addCriterion("callback_code is not null");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeEqualTo(String value) {
            addCriterion("callback_code =", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeNotEqualTo(String value) {
            addCriterion("callback_code <>", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeGreaterThan(String value) {
            addCriterion("callback_code >", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeGreaterThanOrEqualTo(String value) {
            addCriterion("callback_code >=", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeLessThan(String value) {
            addCriterion("callback_code <", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeLessThanOrEqualTo(String value) {
            addCriterion("callback_code <=", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeLike(String value) {
            addCriterion("callback_code like", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeNotLike(String value) {
            addCriterion("callback_code not like", value, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeIn(List<String> values) {
            addCriterion("callback_code in", values, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeNotIn(List<String> values) {
            addCriterion("callback_code not in", values, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeBetween(String value1, String value2) {
            addCriterion("callback_code between", value1, value2, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andCallbackCodeNotBetween(String value1, String value2) {
            addCriterion("callback_code not between", value1, value2, "callbackCode");
            return (Criteria) this;
        }

        public Criteria andStorePathIsNull() {
            addCriterion("store_path is null");
            return (Criteria) this;
        }

        public Criteria andStorePathIsNotNull() {
            addCriterion("store_path is not null");
            return (Criteria) this;
        }

        public Criteria andStorePathEqualTo(String value) {
            addCriterion("store_path =", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathNotEqualTo(String value) {
            addCriterion("store_path <>", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathGreaterThan(String value) {
            addCriterion("store_path >", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathGreaterThanOrEqualTo(String value) {
            addCriterion("store_path >=", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathLessThan(String value) {
            addCriterion("store_path <", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathLessThanOrEqualTo(String value) {
            addCriterion("store_path <=", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathLike(String value) {
            addCriterion("store_path like", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathNotLike(String value) {
            addCriterion("store_path not like", value, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathIn(List<String> values) {
            addCriterion("store_path in", values, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathNotIn(List<String> values) {
            addCriterion("store_path not in", values, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathBetween(String value1, String value2) {
            addCriterion("store_path between", value1, value2, "storePath");
            return (Criteria) this;
        }

        public Criteria andStorePathNotBetween(String value1, String value2) {
            addCriterion("store_path not between", value1, value2, "storePath");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Long value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Long value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Long value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Long value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Long value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Long> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Long> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Long value1, Long value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Long value1, Long value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNull() {
            addCriterion("delete_time is null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNotNull() {
            addCriterion("delete_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeEqualTo(Long value) {
            addCriterion("delete_time =", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotEqualTo(Long value) {
            addCriterion("delete_time <>", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThan(Long value) {
            addCriterion("delete_time >", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("delete_time >=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThan(Long value) {
            addCriterion("delete_time <", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThanOrEqualTo(Long value) {
            addCriterion("delete_time <=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIn(List<Long> values) {
            addCriterion("delete_time in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotIn(List<Long> values) {
            addCriterion("delete_time not in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeBetween(Long value1, Long value2) {
            addCriterion("delete_time between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotBetween(Long value1, Long value2) {
            addCriterion("delete_time not between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andTasktagIsNull() {
            addCriterion("tasktag is null");
            return (Criteria) this;
        }

        public Criteria andTasktagIsNotNull() {
            addCriterion("tasktag is not null");
            return (Criteria) this;
        }

        public Criteria andTasktagEqualTo(String value) {
            addCriterion("tasktag =", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagNotEqualTo(String value) {
            addCriterion("tasktag <>", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagGreaterThan(String value) {
            addCriterion("tasktag >", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagGreaterThanOrEqualTo(String value) {
            addCriterion("tasktag >=", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagLessThan(String value) {
            addCriterion("tasktag <", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagLessThanOrEqualTo(String value) {
            addCriterion("tasktag <=", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagLike(String value) {
            addCriterion("tasktag like", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagNotLike(String value) {
            addCriterion("tasktag not like", value, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagIn(List<String> values) {
            addCriterion("tasktag in", values, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagNotIn(List<String> values) {
            addCriterion("tasktag not in", values, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagBetween(String value1, String value2) {
            addCriterion("tasktag between", value1, value2, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTasktagNotBetween(String value1, String value2) {
            addCriterion("tasktag not between", value1, value2, "tasktag");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("task_type is null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("task_type is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeEqualTo(String value) {
            addCriterion("task_type =", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotEqualTo(String value) {
            addCriterion("task_type <>", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThan(String value) {
            addCriterion("task_type >", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(String value) {
            addCriterion("task_type >=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThan(String value) {
            addCriterion("task_type <", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(String value) {
            addCriterion("task_type <=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLike(String value) {
            addCriterion("task_type like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotLike(String value) {
            addCriterion("task_type not like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIn(List<String> values) {
            addCriterion("task_type in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotIn(List<String> values) {
            addCriterion("task_type not in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeBetween(String value1, String value2) {
            addCriterion("task_type between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotBetween(String value1, String value2) {
            addCriterion("task_type not between", value1, value2, "taskType");
            return (Criteria) this;
        }
        
        public Criteria andClientCallbackedEqualTo(Byte value) {
            addCriterion("client_callbacked =", value, "clientCallbacked");
            return (Criteria) this;
        } 
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pre_dist_task
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 11 11:59:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pre_dist_task
     *
     * @mbggenerated Wed Mar 11 11:59:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}