package com.letv.cdn.openapi.pojo;

public class SubFileResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_file_result.id
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_file_result.outkey
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    private String outkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_file_result.md5
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_file_result.status
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_file_result.tag
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_file_result.user
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    private String user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_file_result.id
     *
     * @return the value of sub_file_result.id
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_file_result.id
     *
     * @param id the value for sub_file_result.id
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_file_result.outkey
     *
     * @return the value of sub_file_result.outkey
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public String getOutkey() {
        return outkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_file_result.outkey
     *
     * @param outkey the value for sub_file_result.outkey
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public void setOutkey(String outkey) {
        this.outkey = outkey == null ? null : outkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_file_result.md5
     *
     * @return the value of sub_file_result.md5
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_file_result.md5
     *
     * @param md5 the value for sub_file_result.md5
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_file_result.status
     *
     * @return the value of sub_file_result.status
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_file_result.status
     *
     * @param status the value for sub_file_result.status
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_file_result.tag
     *
     * @return the value of sub_file_result.tag
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_file_result.tag
     *
     * @param tag the value for sub_file_result.tag
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_file_result.user
     *
     * @return the value of sub_file_result.user
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_file_result.user
     *
     * @param user the value for sub_file_result.user
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    public SubFileResult() {
        super();
    }

    public SubFileResult(String outkey, String md5, Integer status, String tag, String user) {
        super();
        this.outkey = outkey;
        this.md5 = md5;
        this.status = status;
        this.tag = tag;
        this.user = user;
    }
    
    
}