package com.letv.cdn.openapi.dao.report;

import com.letv.cdn.openapi.pojo.Domain;
import com.letv.cdn.openapi.pojo.DomainExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int countByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int deleteByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int insertSelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    List<Domain> selectByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    Domain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int updateByExample(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int updateByPrimaryKeySelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Tue Jan 06 16:55:03 CST 2015
     */
    int updateByPrimaryKey(Domain record);
}