package com.letv.cdn.openapi.dao.report;

import com.letv.cdn.openapi.pojo.SubFileResult;
import com.letv.cdn.openapi.pojo.SubFileResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubFileResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int countByExample(SubFileResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int deleteByExample(SubFileResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int insert(SubFileResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int insertSelective(SubFileResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    List<SubFileResult> selectByExample(SubFileResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    SubFileResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int updateByExampleSelective(@Param("record") SubFileResult record, @Param("example") SubFileResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int updateByExample(@Param("record") SubFileResult record, @Param("example") SubFileResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int updateByPrimaryKeySelective(SubFileResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_file_result
     *
     * @mbggenerated Fri Nov 07 16:06:40 CST 2014
     */
    int updateByPrimaryKey(SubFileResult record);
}