package com.letv.cdn.openapi.dao.domain;

import com.letv.cdn.openapi.pojo.CoopDomain;
import com.letv.cdn.openapi.pojo.CoopDomainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoopDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int countByExample(CoopDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int deleteByExample(CoopDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int deleteByPrimaryKey(String domain);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int insert(CoopDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int insertSelective(CoopDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    List<CoopDomain> selectByExample(CoopDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    CoopDomain selectByPrimaryKey(String domain);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") CoopDomain record, @Param("example") CoopDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int updateByExample(@Param("record") CoopDomain record, @Param("example") CoopDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int updateByPrimaryKeySelective(CoopDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coop_domain
     *
     * @mbggenerated Tue Nov 04 09:32:42 CST 2014
     */
    int updateByPrimaryKey(CoopDomain record);
}